
[logger]
type = "debug"
[[logger.rules.rules]]
pattern = "^debug"

[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcScIYJ6sUikhzfgkkc8Wf6aHhBf3i9qjX4NJi537j8cj8uzjnOoeKEag6nfx4i"
key_file = "./priv.key"

[[dnas]]
id = "chat_dna"
file = "dna/holo-chat.hcpkg"

[[instances]]
id = "holo-chat"
dna = "chat_dna"
agent = "test_agent1"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "storage"

[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3400
[[interfaces.instances]]
id = "holo-chat"

[[ui_bundles]]
id = "main"
root_dir = "./ui"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 3000
dna_interface = "websocket_interface"

[network]
n3h_path = "./n3h"
n3h_log_level = "i"
n3h_persistence_path = "./n3hfolder"
bootstrap_nodes=["wss://99.224.95.144:5555/?a=HcSci3EmBbcFkzc5d3SiDOxooCmo47qj39oSv4H4vMGT4xow5ybXq7bq73C53hr"]